name: PlayerProfiles
main: me.Zonr0.PlayerProfiles.PlayerProfiles
version: "0.1.1"
commands:
    debug:
        description: Prints debugging information.
        permission: PlayerProfiles.debug
        usage:   |
          /debug
    profile:
        description: handles the player profile registration and viewing.
        permission: playerProfiles.profile
        usage:   |
         /profile register
         /profile view <target>